// Generated by CoffeeScript 1.6.3
(function() {
  var bindArray, bindAttributeObject, bindData, bindNestedObject, bindObject, bindOrRemove, bindValue, facile, find, setAttributeValue, startProcessing, tagName;

  facile = function(template, data, domModule) {
    var $template;
    this.$ = domModule || this.$;
    $template = $('<div />').append($(template));
    return startProcessing($template, data);
  };

  facile.update = startProcessing = function($template, data) {
    var key, value;
    for (key in data) {
      value = data[key];
      bindOrRemove($template, key, value);
    }
    return $template.html();
  };

  find = function($el, key) {
    var $result;
    $result = $el.find('#' + key);
    if ($result.length === 0) {
      $result = $el.find('.' + key);
    }
    return $result;
  };

  bindOrRemove = function($template, key, value) {
    var $el;
    if (value != null) {
      return bindData($template, key, value);
    } else {
      $el = find($template, key);
      return $el.remove();
    }
  };

  bindData = function($template, key, value) {
    var $target;
    if (value.constructor === Array) {
      return bindArray($template, key, value);
    } else if (value.constructor === Object) {
      $target = find($template, key);
      return bindObject($target, key, value);
    } else {
      return bindValue($template, key, value);
    }
  };

  bindArray = function($template, key, value) {
    var $child, $clone, $nested, $root, arrayValue, newHtml, _i, _len, _results;
    $root = find($template, key);
    if ($root.length === 0) {
      return;
    }
    $nested = find($root, key);
    if ($nested.length > 0) {
      $root = $nested;
    }
    if (tagName($root) === "TABLE") {
      $root = $root.find('tbody');
    }
    $child = $root.children().remove();
    _results = [];
    for (_i = 0, _len = value.length; _i < _len; _i++) {
      arrayValue = value[_i];
      $clone = $child.clone();
      if (arrayValue.constructor === Object) {
        newHtml = facile($clone, arrayValue);
        _results.push($root.append(newHtml));
      } else {
        $clone.html(arrayValue);
        _results.push($root.before($clone));
      }
    }
    return _results;
  };

  bindObject = function($template, key, value) {
    if (value.content != null) {
      return bindAttributeObject($template, key, value);
    } else {
      return bindNestedObject($template, key, value);
    }
  };

  tagName = function($el) {
    if ($el.prop) {
      return $el.prop("tagName");
    } else {
      return $el[0].name.toUpperCase();
    }
  };

  bindValue = function($template, key, value) {
    var $el, attr, _ref;
    if (key.indexOf('@') !== -1) {
      _ref = key.split('@'), key = _ref[0], attr = _ref[1];
      $el = find($template, key);
      if (tagName($el) === 'SELECT') {
        return $el.find("option[value='" + value + "']").attr('selected', 'selected');
      } else {
        return setAttributeValue($el, attr, value);
      }
    } else {
      $el = find($template, key);
      if ($el.length > 0) {
        if (tagName($el) === 'INPUT' && $el.attr('type') === 'checkbox' && value) {
          return $el.attr('checked', "checked");
        } else if (tagName($el) === 'INPUT' || tagName($el) === 'OPTION') {
          return $el.attr('value', '' + value);
        } else if (tagName($el) === 'SELECT' && value.constructor !== Object) {
          return $el.find("option[value='" + value + "']").attr('selected', 'selected');
        } else {
          return $el.html('' + value);
        }
      }
    }
  };

  bindNestedObject = function($template, key, value) {
    var attr, attrValue, _results;
    _results = [];
    for (attr in value) {
      attrValue = value[attr];
      _results.push(bindOrRemove($template, attr, attrValue));
    }
    return _results;
  };

  bindAttributeObject = function($template, key, value) {
    var attr, attrValue, _results;
    $template.html(value.content);
    _results = [];
    for (attr in value) {
      attrValue = value[attr];
      if (attr !== 'content') {
        _results.push(setAttributeValue($template, attr, attrValue));
      }
    }
    return _results;
  };

  setAttributeValue = function($el, attr, value) {
    var dataAttr;
    if (attr === 'class') {
      return $el.addClass(value);
    }
    if (attr.indexOf('data-') === 0) {
      dataAttr = attr.substr(5);
      return $el.data(dataAttr, value);
    } else {
      return $el.attr(attr, value);
    }
  };

  if (typeof window !== "undefined" && window !== null) {
    window.facile = facile;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = facile;
  }

}).call(this);
